spyder/common/urls.py
from django.urls import path
from . import views

app_name = 'common'



urlpatterns=[    
   
    path('customersignup/',views.common_customersignup, name='common_customersignup'),
    path('login/',views.common_login, name='common_login'),
    path('sellerlogin/',views.common_sellerlogin, name='common_sellerlogin'),
    path('index/',views.common_index, name='common_index'),
    path('sellersignup/',views.common_sellersignup, name='common_sellersignup'),
    
    
    
    
    
    
    
    ]

spyder/customer/urls.py
from django.urls import path
from . import views

app_name = 'customer'



urlpatterns=[    
   
    path('buy/',views.customer_buy, name='customer_buy'),
    path('index/',views.customer_index, name='customer_index'),
    path('mycart/',views.cutomer_mycart, name='mycart'),
    path('myorder/',views.customer_myorder, name='customer_myorder'),
    path('passwordchange/',views.customer_passwordchange, name='customer_passwordchange'),
    path('productdetails/',views.customer_productdetails, name='customer_productdetails'),
    path('profile/',views.customer_profile, name='customer_profile'),
    path('update/',views.customer_update, name='customer_update'),
    
    
]
    
    
    
    
    
    

spyder/eco_admin/urls.py
from django.urls import path
from . import views

app_name = 'eco_admin'



urlpatterns=[    
   
    path('approveseller/',views.eadmin_approveseller, name='eadmin_approveseller'),
    path('index/',views.eadmin_index, name='eadmin_index'),
    path('login/',views.eadmin_login, name='eadmin_login'),
    path('removecustomer/',views.eadmin_removecustomer, name='eadmin_removecustomer'),
    path('removepro/',views.eadmin_removepro, name='eadmin_removepro'),
    path('removeseller/',views.eadmin_removeseller, name='eadmin_removeseller'),
    path('viewcustomer/',views.eadmin_viewcustomer, name='eadmin_viewcustomer'),
    path('viewproducts/',views.eadmin_viewproducts, name='eadmin_viewproducts'),
    path('viewseller/',views.eadmin_viewseller, name='eadmin_viewseller'),
    
    
    
    
    
    
    
    ]

spyder/seller/urls.py
from django.urls import path
from . import views

app_name = 'seller'



urlpatterns=[    
   
    path('addproduct/',views.seller_addproduct, name='seller_addproduct'),
    path('changepassword/',views.seller_changepassword, name='seller_changepassword'),
    path('index/',views.seller_index, name='seller_index'),
    path('productcatelogue/',views.seller_productcatelogue, name='seller_productcatelogue'),
    path('profile/',views.seller_profile, name='seller_profile'),
    path('recentorders/',views.seller_recentorders, name='seller_recentorders'),
    path('update/',views.seller_update, name='seller_update'),
    path('updatestock/',views.seller_updatestock, name='seller_updatestock'),
    
    
    
    
    
    
    
    
    ]

spyder/spyder/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('common/',include('common.urls')),
    path('eco_admin/',include('eco_admin.urls')),
    path('seller/',include('seller.urls')),
    path('customer/',include('customer.urls')),
     
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

spyder/common/models.py
from django.db import models

# Create your models here.
class Cutomer(models.Model):
      customer_name = models.CharField(max_length =50)
      gender = models.CharField(max_length=50)
      email = models.CharField (max_length=50)
      customer_phonenumber = models.CharField (max_length=50)
      customer_address = models.CharField (max_length=500)
      customer_password = models.CharField (max_length=150)
      customer_image = models.ImageField(upload_to='customer/')

      class Meta:
            db_table = 'customer_tb'

spyder/customer/models.py
from django.db import models

# Create your models here.

spyder/eco_admin/models.py
from django.db import models

# Create your models here.

spyder/seller/models.py
from django.db import models

# Create your models here.

spyder/common/views.py
from django.shortcuts import render

from common.models import Cutomer

# Create your views here.
def common_index(request):
    return render(request,'common_temp/index.html')
def common_customersignup(request):
    if request.method == 'POST':
        customer_name = request.POST['c_name']
        customer_gender = request.POST['c_gender']
        customer_email = request.POST['c_email']
        customer_phone = request.POST['phone']
        customer_address= request.POST['c_address']
        customer_password= request.POST['pass']
        customer_image= request.FILES['img']

        new_customer = Cutomer(
            customer_name = customer_name,
            gender = customer_gender,
            email     = customer_email ,
            customer_phonenumber =  customer_phone,
            customer_address = customer_address,
            customer_password = customer_password ,
            customer_image = customer_image 

        ) 
        new_customer.save()

def customer_login(request):
    msg = ''
    if request.method == 'POST':
       cust_email = request.POST['custid']
       cust_psw = request.POST['psw']
    try:
      customer = Customer.objects.get(e_mail = cust_email,password = )
      request.session['customer'] = customer.id
      return redirect('customer:home')
    except:
            msg = "Invalid Email ID or Password"
   




    return render(request,'common_temp/customersignup.html')  
def common_login(request):
    return render(request,'common_temp/login.html')  
def common_sellerlogin(request):
    return render(request,'common_temp/sellerlogin.html')
def common_sellersignup(request):
    return render(request,'common_temp/sellersignup.html')

spyder/customer/views.py
from django.shortcuts import render

# Create your views here.
def customer_buy(request):
    return render(request,'customertemp/buy.html')
def customer_index(request):
    return render(request,'customertemp/index.html')  
def cutomer_mycart(request):
    return render(request,'customertemp/mycart.html')  
def customer_myorder(request):
    return render(request,'customertemp/myorder.html')
def customer_passwordchange(request):
    return render(request,'customertemp/passwordchange.html')
def customer_productdetails(request):
    return render(request,'customertemp/productdetails.html')
def customer_profile(request):
    return render(request,'customertemp/profile.html')  
def customer_update(request):
    return render(request,'customertemp/update.html')  

spyder/eco_admin/views.py
from django.shortcuts import render

# Create your views here.
def eadmin_approveseller(request):
    return render(request,'spideradmintemp/approveseller.html')
def eadmin_index(request):
    return render(request,'spideradmintemp/index.html')  
def eadmin_login(request):
    return render(request,'spideradmintemp/login.html')  
def eadmin_removecustomer(request):
    return render(request,'spideradmintemp/removecustomer.html')
def eadmin_removepro(request):
    return render(request,'spideradmintemp/removepro.html')
def eadmin_removeseller(request):
    return render(request,'spideradmintemp/removeseller.html')
def eadmin_viewcustomer(request):
    return render(request,'spideradmintemp/viewcustomer.html')  
def eadmin_viewproducts(request):
    return render(request,'spideradmintemp/viewproducts.html')  
def eadmin_viewseller(request):
    return render(request,'spideradmintemp/viewseller.html')

spyder/seller/views.py
from django.shortcuts import render

# Create your views here.
def seller_addproduct(request):
    return render(request,'resellertemp/addproduct.html')
def seller_changepassword(request):
    return render(request,'resellertemp/changepassword.html')  
def seller_index(request):
    return render(request,'resellertemp/index.html')  
def seller_productcatelogue(request):
    return render(request,'resellertemp/productcatelogue.html')
def seller_profile(request):
    return render(request,'resellertemp/profile.html')
def seller_recentorders(request):
    return render(request,'resellertemp/recentorders.html')
def seller_update(request):
    return render(request,'resellertemp/update.html')  
def seller_updatestock(request):
    return render(request,'resellertemp/updatestock.html')  

spyder/customer/templates/customertemp/masterpage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spyder</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
  
    
</head>
<body style="background-color: #e6e6e6;">
  <header style="background-image:linear-gradient(#292929, #060605);" class="sticky-top" >
    <div class="container-fluid">
  
      <!-- navbar -->
          <div class="col-md-12 col-12 ">
            <nav style="background-image: linear-gradient(#292929, #060605);" class="navbar navbar-expand-lg navbar-dark">
              <a class="navbar-brand" href="#">
                <img src="{% static 'images/Spyder logo.png' %}" width="120" class="img-fluid"/>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url 'customer:customer_index' %}"><small>PRODUCTS</small><span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="about.html"><small>SPYDER TEAM</small> <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="about.html"><small>ABOUT US </small><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'customer:customer_profile' %}"><small>PROFILE </small><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'customer:customer_myorder' %}"><small>ORDERS</small> <span class="sr-only"></span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'customer:mycart' %}"><small>My CART</small> <span class="sr-only">(current)</span></a>
                    </li>     
                    <li class="nav-item active">
                      <img src="{% static 'images/vvt.png' %}" height="20px" width="60px" class="mt-2 ml-5">
                    </li>      
                </ul>
                
                <form class="form-inline my-2 my-lg-0">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'customer:mycart' %}"><span class="text-secondary"><img src="{% static 'images/cart.png' %}" height="20px" width="20px" >Cart</span><span class="sr-only">(current)</span></a>
                    </li> 
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Logout
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                          <a class="dropdown-item" href="{% url 'customer:customer_profile' %}">Profile</a>
                          <a class="dropdown-item" href="{% url 'customer:customer_passwordchange' %}">Change Password</a>
                          <a class="dropdown-item" href="">Logout</a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="#"><span class="text-secondary">Search</span><span class="sr-only">(current)</span></a>
                    </li>  
                  </ul>
                </form>
              </div>
              </div>
            </nav>

      </div>
  </div>
</div>
</header>
{% block content %}
{% endblock %}
<!-- Footer -->
<footer style="background-color: #060605;" class="mt-3">
 <div class="container-fluid">
  <div class="row" style="font-size: 10px;">
    <div class="col-12">
    
    <ul class="nav justify-content-center">
      <li class="nav-item">
        <span class="nav-link disabled">Privacy Policy</span>
      </li>
      <li class="nav-item">
        <span class="nav-link disabled">Warranty</span>
      </li>
      <li class="nav-item">
        <span class="nav-link disabled">FAQ</span>
      </li>
      <li class="nav-item">
        <span class="nav-link disabled">Contact</span>
      </li>
      <li class="nav-item">
        <span class="nav-link disabled">Social Media</span>
      </li>
      <li class="nav-item">
        <span class="nav-link disabled">Dealer Login</span>
      </li>
      <li class="nav-item">
        <span class="nav-link disabled">VIP Login</span>
      </li>
      <li class="nav-item">
        <span class="nav-link disabled">Blog</span>
      </li>
      <li class="nav-item">
        <span class="nav-link disabled">Corporate & Uniform Sales</span>
      </li>
    </ul>
  </div>
  </div>
  <!-- Our Partner row -->
  <div class="row pl-2 pt-3 pb-4"  style="font-size: 10px;"> 
    <!-- Our Partner Column -->
    <div class="col-12 col-md-3">
      <span class="text-secondary">OUR PARTNERS</span>
    </div>

    <!-- Images Column -->
    <div class="col-12 col-md-9 p-3">
      <img src="{% static 'images/download-removebg-preview.png' %}" height="25px" width="70px">
      <img src="{% static 'images/audi-logo-9C21D639E0-seeklogo.com-removebg-preview (1).png' %}"  height="25px" width="70px">
      <img src="{% static 'images/alpine-canada-removebg-preview.png' %}" height="25px" width="70px">
      <img src="{% static 'images/cal.png' %}" height="25px" width="70px">
      <img src="{% static 'images/mc.png' %}" height="25px" width="70px">
      <img src="{% static 'images/us.png' %}" height="25px" width="70px">
    </div>
  </div>
 </div>
  
</footer>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

spyder/eco_admin/templates/spideradmintemp/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Spyder</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style/style.css' %}">

</head>
<body style="background-color: #e6e6e6;">
  <header style="background-image:linear-gradient(#292929, #060605);"  >
    <div class="container-fluid">
  
      <!-- navbar -->
          <div class="col-md-12 col-12 ">
            <nav style="background-image: linear-gradient(#292929, #060605);" class="navbar navbar-expand-lg navbar-dark fixed-top">
              <a class="navbar-brand" href="#">
                <img src="{% static 'images/Spyder logo.png' %}" width="120" class="img-fluid"/>
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  <li class="nav-item active">
                    <a class="nav-link" href="about.html"><small>PRODUCTS</small><span class="sr-only">(current)</span></a>
                  </li>
                  <li class="nav-item active">
                      <a class="nav-link" href="about.html"><small>SPYDER TEAM</small> <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="about.html"><small>ABOUT US </small><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="about.html"><small>NEWS </small><span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="about.html"><small>PASSION</small> <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                      <a class="nav-link" href="contact.html"><small>CONTACT</small> <span class="sr-only">(current)</span></a>
                    </li>     
                    <li class="nav-item active">
                      <img src="{% static 'images/vvt.png' %}" height="20px" width="60px" class="mt-2 ml-5">
                    </li>      
                  
                </ul>
                
                <form class="form-inline my-2 my-lg-0">
                  <ul class="navbar-nav mr-auto">
                    
                    <li class="nav-item active">
                      <a class="nav-link" href="#"><span class="text-secondary">Search</span><span class="sr-only">(current)</span></a>
                    </li>  
                    <li class="nav-item active">
                        <a class="nav-link" href=""><span class="text-secondary">Logout</span><span class="sr-only">(current)</span></a>
                      </li>  
                    
                  </ul>
                </form>
              </div>
            </nav>

      </div>
  </div>
</div>
</header>
<!-- Next Section or Row -->

<!-- Next Section -->
<section>
  <div class="container-fluid">
  <div class="row pt-5">
      <div class="col-12 text-center text-white p-4" style="background-color: #6f7376;">
          <span style="font-size:30px ; color: #c5cace; font-weight: lighter;">Admin Dashboard</span>
      </div>
  </div>
</div>
</section>
<section>
  <div class="container" >
    <div class="row">
      <!-- Card 1 -->
        <div class="col-12 col-md-2 col-sm-6 pt-3"><a href="{% url 'eco_admin:eadmin_approveseller' %}" class="text-dark">
          <div class="card text-center">
            <img src="{% static 'images/2601778.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title font1">Approve Seller</h5>
            </div>
          </div></a>
        </div>
        <!-- Card 2 -->
        <div class="col-12 col-md-2 col-sm-6 pt-3"><a href="{% url 'eco_admin:eadmin_viewseller' %}" class="text-dark">
          <div class="card text-center">
            <img src="{% static 'images/sellerlogo.png' %}"  class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title  font1">View Seller</h5>
            </div>
          </div></a>
        </div>
        <!-- Card 3 -->
        <div class="col-12 col-md-2 col-sm-6 pt-3"><a href="{% url 'eco_admin:eadmin_viewcustomer' %}" class="text-dark">
          <div class="card text-center">
            <img src="{% static 'images/viewcust.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title  font1">View Customer </h5>
               </div>
          </div></a>
        </div>
        <!-- Card 4 -->
        

        <div class="col-12 col-md-2 col-sm-6 pt-3"><a href="{% url 'common:common_login' %}" class="text-dark">
          <div class="card text-center">
            <img src="{% static 'images/vieworder.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title  font1">View Orders</h5>
            </div>
          </div>
        </div></a>
        
    
    <!-- Card 5 -->
    
      <div class="col-12 col-md-2 col-sm-6 pt-3 pb-3"><a href="{% url 'common:common_login' %}" class="text-dark">
        <div class="card text-center">
          <img src="{% static 'images/recentupdate.png' %} " class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title  font1">Recent Updates</h5>
            </div>
        </div></a>
      </div>
      <!-- Card 6 -->
      <div class="col-12 col-md-2 col-sm-6 pt-3 pb-3"><a href="{% url 'eco_admin:eadmin_viewproducts' %}" class="text-dark">
        <div class="card text-center">
          <img src="{% static 'images/viewpro.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title  font1">View Products</h5>
            </div>
        </div></a>
      </div>
      <!-- card 7 -->
      <div class="col-12 col-md-2 col-sm-6 pt-3 pb-3"><a href="{% url 'eco_admin:eadmin_removeseller' %}" class="text-dark">
        <div class="card text-center">
          <img src="{% static 'images/recentupdate.png' %} " class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title  font1">Remove Seller</h5>
            </div>
        </div></a>
      </div>
       <!-- card 8 -->
       <div class="col-12 col-md-2 col-sm-6 pt-3 pb-3"><a href="{% url 'eco_admin:eadmin_removecustomer' %}" class="text-dark">
        <div class="card text-center">
          <img src="{% static 'images/removecustomer.png' %} " height="90px" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title  font1">Remove Customer</h5>
            </div>
        </div></a>
      </div>
       <!-- card 7 -->
       <div class="col-12 col-md-2 col-sm-6 pt-3 pb-3"><a href="{% url 'eco_admin:eadmin_removepro' %}" class="text-dark">
        <div class="card text-center">
          <img src="{% static 'images/removeproduct.png' %} " height="90px" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title  font1">Remove Product</h5>
            </div>
        </div></a>
      </div>
    </div>  
</section>
<!-- Footer -->
<footer style="background-color: #060605;">
 <div class="container-fluid">
  
  <!-- Our Partner row -->
  <div class="row pl-2 pt-3 pb-4"  style="font-size: 10px;"> 
    <!-- Our Partner Column -->
    <div class="col-12 col-md-3">
      <span class="text-secondary">OUR PARTNERS</span>
    </div>

    <!-- Images Column -->
    <div class="col-12 col-md-9 p-3">
      <img src="{% static 'images/download-removebg-preview.png' %}" height="25px" width="70px">
      <img src="{% static 'images/audi-logo-9C21D639E0-seeklogo.com-removebg-preview (1).png' %}"  height="25px" width="70px">
      <img src="{% static 'images/alpine-canada-removebg-preview.png' %}" height="25px" width="70px">
      <img src="{% static 'images/cal.png' %}" height="25px" width="70px">
      <img src="{% static 'images/mc.png' %}" height="25px" width="70px">
      <img src="{% static 'images/us.png' %}" height="25px" width="70px">
    </div>
  </div>
 </div>
  
</footer>
 
      
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
  </html>

spyder/seller/templates/resellertemp/index.html
{% extends 'resellertemp/masterpage.html' %}
{% load static %}
{% block content %}
<section>
  <div class="container mt-5" >
    <div class="row pt-5">
      <!-- Card 1 -->
        <div class="col-12 col-md-2 col-sm-6 pt-3">
          <a href="{% url 'seller:seller_productcatelogue' %}" class="text-dark">
            <div class="card text-center">
              <img src="{% static 'images/procat.png' %}" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title font1">Product Catalogue</h5>
              </div>
            </div>
          </a>
        </div>
        <!-- Card 2 -->
        <div class="col-12 col-md-2 col-sm-6 pt-3"><a href="{% url 'seller:seller_addproduct' %}" class="text-dark">
          <div class="card text-center">
            <img src="{% static 'images/addpro.png' %}"  class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title  font1">Add Product</h5>
            </div>
          </div></a>
        </div>
        <!-- Card 3 -->
        <div class="col-12 col-md-2 col-sm-6 pt-3"><a href="{% url 'seller:seller_updatestock' %}" class="text-dark">
          <div class="card text-center">
            <img src="{% static 'images/recentupdate.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title  font1">Update Stock</h5>
               </div>
          </div></a>
        </div>
        <!-- Card 4 -->
        <div class="col-12 col-md-2 col-sm-6 pt-3"><a href="{% url 'seller:seller_recentorders' %}" class="text-dark">
          <div class="card text-center">
            <img src="{% static 'images/vieworder.png' %}" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title  font1">Recent Orders</h5>
              </div>
          </div>
        </div></a>
    <!-- Card 5 -->
      <div class="col-12 col-md-2 col-sm-6 pt-3 pb-3"><a href="{% url 'common:common_login' %}" class="text-dark">
        <div class="card text-center">
          <img src="{% static 'images/recentupdate.png' %} " class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title  font1">Recent Updates</h5>
            </div>
        </div></a>
      </div>
      <!-- Card 6 -->
      <div class="col-12 col-md-2 col-sm-6 pt-3 pb-3"><a href="{% url 'common:common_login' %}" class="text-dark">
        <div class="card text-center">
          <img src="{% static 'images/orderhist.png' %}" class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title  font1">Order History</h5>
            </div>
        </div></a>
      </div>
     
      
  </div>
  </div>  
</section>

      
  </body>
  </html>
  {% endblock %}